# Profile section
profile:
  first_name: Gilvan
  last_name: Almeida
  picture: static/img/perfil.jpg # Local picture
  contact:
    address_one: Rio de Janeiro, Brazil
    address_two:
    phone: +55 21 982689057
  email: gilvan.praxedes@outlook.com
  description: >
    I'm a bachelor's Computer Science, M.Sc. student at Military Institute of Engineering - IME/RJ, studying machine learning techniques, graduated in Computer Science at Centro Universitário Carioca - Unicarioca(2018). 
    I'm passionate about how technology can change the world, enthusiast about programming languages, process optimization, ETL and technologies in general. Trying to learn everything I can and apply it so I can help companies grow their business. If you have a project I can help with, please get in touch.

# Social section
social:
  github: https://github.com/iamgilvan
  linkedin: https://www.linkedin.com/in/gilvan-almeida/
  facebook: https://www.facebook.com/gilvan.praxedes
  instagram: https://www.instagram.com/gilvanpraxedes/
  medium: https://medium.com/@iamgilvan


# Experience section
experience:
  item0:
    position: Software Analyst
    company: Radix Engenharia e Software
    from: May 2019
    to: Present
    description: > 
    link: http://www.radixeng.com.br/
  item1:
    position: Software Developer
    company: BigData Corp.
    from: February 2019
    to: April 2019
    description: >
      Development and administration of automated processes, API's to generate reports and business intelligence solutions. Services development based on cloud. Massive use of development based on cloud services, such as Amazon Web Services and Microsoft Azure.
    link: https://bigdatacorp.com.br/
  item2:
    position:  Software Developer Internship
    company: BigData Corp.
    from: September 2017
    to: January 2019
    description: >
      Development of automated processes to generate reports and business intelligence solutions. Services development based on cloud. Massive use of cloud services, such as Amazon Web Services (S3, SQS, EC2). 
    link: https://bigdatacorp.com.br/
  item3:
    position: Developer Internship
    company: Fiocruz
    from: November 2014
    to: September 2017
    description: >
      Member of the project's support and development team Institutional Repository of Fiocruz Arca, which stores the intellectual, scientific and academic production of the institution. Analysis, debugging, script development for the optimization of import and export records. Queries, update , dump and restore in the database.
    link: https://portal.fiocruz.br/


# Education section
education:
  item1:
    institution: Military Institute of Engineering - IME/RJ
    program:  Master in System and Computing
    description: Development, analysis and research of machine learning techniques.
    from: February 2020
    to: Present
  item2:
    institution: Centro Universitário Carioca - Unicarioca/RJ
    program: >
      Bachelor's Degree in Computer Science
    description: Computer/Information Technology Administration and Management
    from: July 2013
    to: December 2018

# Skills section
tools:
  # Consider that the following are icons:
  #   https://icons8.com/icons
  item1:
    img: c-sharp-logo-2
    title: C#
  item2:
    img: python
    title: Python
  item3:
    img: mysql-logo
    title: Mysql
  item4:
    img: angularjs
    title: Angular
  item5:
    img: docker
    title: Docker
  item6:
    img: linux
    title: Linux 
  item7:
    img: c-plus-plus-logo
    title: C++
  item8:
    img: django
    title: Django
  item9:
    img: microsoft-sql-server
    title: Sql Server
  item10:
    img: java-coffee-cup-logo
    title: Java
  item11:
    img: amazon-web-services
    title: AWS Services
  item12:
    img: postgreesql
    title: Postgreesql
  item13:
    img: sql
    title: Sql
  item14:
    img: mongodb
    title: MongoDB
  item15:
    img: github
    title: Git
    
extra_skills:
  - Flask
  - Web scraping and web automation
  - APIs and web development
  - Unit Testing
  - Problem Solving
  - Cloud Computing
  - Analytical Skills
  - Scripting
  - DevOps
  - Machine learning
  - Training and Development


# Talks and workshops section
workshops:
  item0:
    event: AWS Innovate
    workshop: AWS Innovate Online Conference, January 2020.
    material:
    link: https://aws.amazon.com/pt/latam-pt-innovate/
  item1:
    event: AWS Innovate Machine Learning & AI Edition
    workshop: AWS Innovate Online Conference, January 2020.
    material:
    link: https://aws.amazon.com/pt/events/aws-innovate/machine-learning/

# Projects section
projects:
  item1:
    title: flask resume template
    subtitle: A resume template built with Flask
    description: An easy-to-configure simple resume template built with Flask and Bootstrap.
    github: https://github.com/iamgilvan/flask-resume
    tags: [Flask, Python, Bootstrap]
  item3:
    title: TDD Python Example
    subtitle: Unit Test
    description: Unit test example development in python
    github: https://github.com/iamgilvan/tdd-python-example
    tags: [Python, Unit Test, PyTest]
  item4:
    title: Conversions of currencies
    subtitle: Conversions between different currencies
    description: The main objective of this API developed in Python, is to make conversions between different currencies with real and current quotes.
    github: https://github.com/iamgilvan/challenger-bravo
    tags: [Python, Flask, MongoDb, Heroku]
  item6:
    title: Airbnb Predict Price
    subtitle: Investigating Airbnb activity in Berlin, Germany
    description: ""
    github: https://gist.github.com/iamgilvan/73e2fc5864e4b3dd3c515028d114c488
    tags: [Python, Scikit-Learn, Matplotlib, Seaborn, Numpy, Pandas, Decision Tree Regressor]
  item7:
    title: Airbnb Predict Demands
    subtitle: Investigating Airbnb activity in Berlin, Germany
    description: ""
    github: https://gist.github.com/iamgilvan/06786c9ee39df937cbb04e895b0a5ab3
    tags: [Python, Matplotlib, Seaborn, Numpy, Pandas]
  item9:
    title: Natural language processing 
    subtitle: Natural language processing exercice
    description: " "
    github: https://gist.github.com/iamgilvan/2c28d243922980f9c91113da12951388
    img: simple-omnitrix.png
    tags: [Python, Pandas, Scikit-Learn, Nltk]
